package com.cotiviti.hdap.APIPayLoads;

import java.util.concurrent.ConcurrentHashMap;

import com.cotiviti.hdap.APICommonLibrary.apiCommonLib;

public class RequestGroupConfigSettings extends apiCommonLib{

	public String requestGroupConfigSettingPayload(ConcurrentHashMap<String,String>objMap) {		
		
		String rgName = objMap.get("RGName");
		String timeZone = objMap.get("TimeZone");
		String endTime = objMap.get("EndTime");
		String startTime = objMap.get("StartTime");
		String nextReviewDate = objMap.get("NextReviewDate");
		String AdditionalNotes  ;
		if(!(objMap.get("AdditionalNotes").isEmpty() && objMap.get("AdditionalNotes") != null) &&
				objMap.get("AdditionalNotes").equalsIgnoreCase("")) {
			
			AdditionalNotes = objMap.get("AdditionalNotes");
		}else {
			AdditionalNotes = "This is created through Automation";
		}
			
		String configPayloadRG = "{\r\n"
			    + "    \"RequestGroupName\": \""+rgName+"\",\r\n"
			    + "    \"ContactPreferences\": {\r\n"
			    + "        \"TimeZone\": \""+timeZone+"\",\r\n"
			    + "        \"Preferences\": [\r\n"
			    + "            {\r\n"
			    + "                \"DayOfWeek\": \"Monday\",\r\n"
			    + "                \"EndTime\": \""+endTime+"\",\r\n"
			    + "                \"StartTime\": \""+startTime+"\"\r\n"
			    + "            },\r\n"
			    + "            { \"DayOfWeek\": \"Tuesday\" },\r\n"
			    + "            { \"DayOfWeek\": \"Wednesday\" },\r\n"
			    + "            { \"DayOfWeek\": \"Thursday\" },\r\n"
			    + "            { \"DayOfWeek\": \"Friday\" },\r\n"
			    + "            { \"DayOfWeek\": \"Saturday\" },\r\n"
			    + "            {\r\n"
			    + "                \"DayOfWeek\": \"Sunday\",\r\n"
			    + "                \"EndTime\": \"5:31 AM\",\r\n"
			    + "                \"StartTime\": \"5:28 AM\"\r\n"
			    + "            }\r\n"
			    + "        ]\r\n"
			    + "    },\r\n"
			    + "    \"LetterPreference\": {\r\n"
			    + "        \"IsValidated\": true,\r\n"
			    + "        \"AdditionalNotes\": \""+AdditionalNotes+"\",\r\n"
			    + "        \"GroupLetterInBatch\": true,\r\n"
			    + "        \"Preference\": \"RequestGroup\",\r\n"
			    + "        \"LettersPerBatch\": 4,\r\n"
			    + "        \"AdditionalData\": {\r\n"
			    + "            \"AdditionalNote\": true,\r\n"
			    + "            \"ClaimEntity\": true,\r\n"
			    + "            \"DateOfService\": true,\r\n"
			    + "            \"FacilityAddress\": true,\r\n"
			    + "            \"PatientAddress\": true,\r\n"
			    + "            \"PatientAge\": true,\r\n"
			    + "            \"PatientDOB\": true,\r\n"
			    + "            \"PatientEmail\": true,\r\n"
			    + "            \"PatientName\": true,\r\n"
			    + "            \"PatientPhone\": true,\r\n"
			    + "            \"Project\": true,\r\n"
			    + "            \"ProviderName\": true,\r\n"
			    + "            \"ProviderVerification\": true,\r\n"
			    + "            \"Gender\": true,\r\n"
			    + "            \"CotivitiPhoneNumber\": false,\r\n"
			    + "            \"CallCenterCallTimes\": true,\r\n"
			    + "            \"NPI\": false,\r\n"
			    + "            \"TIN\": true,\r\n"
			    + "            \"SSN\": false,\r\n"
			    + "            \"HICN\": false,\r\n"
			    + "            \"MBI\": true,\r\n"
			    + "            \"CommitmentDate\": false,\r\n"
			    + "            \"ProjectedCopyDate\": true,\r\n"
			    + "            \"LastDateSent\": false,\r\n"
			    + "            \"TypeofRecord\": true,\r\n"
			    + "            \"PaidAmount\": true,\r\n"
			    + "            \"PlanName\": false,\r\n"
			    + "            \"SentCount\": true,\r\n"
			    + "            \"PatientAddressLine1\": true,\r\n"
			    + "            \"PatientAddressLine2\": false,\r\n"
			    + "            \"City\": true,\r\n"
			    + "            \"State\": false,\r\n"
			    + "            \"Zip\": false,\r\n"
			    + "            \"AdditionalNoteText\": \"This is an additional note entered by the user.\"\r\n"
			    + "        }\r\n"
			    + "    },\r\n"
			    + "    \"MainAddress\": {\r\n"
			    + "        \"IsValidated\": true,\r\n"
			    + "        \"AddressLine1\": \"234\",\r\n"
			    + "        \"AddressLine2\": \"234\",\r\n"
			    + "        \"AttnTo\": \"324\",\r\n"
			    + "        \"City\": \"234\",\r\n"
			    + "        \"State\": \"HI\",\r\n"
			    + "        \"Zip\": \"22222-2222\"\r\n"
			    + "    },\r\n"
			    + "    \"PaymentPreference\": {\r\n"
			    + "        \"IsValidated\": true,\r\n"
			    + "        \"PayVia\": \"Phone\",\r\n"
			    + "        \"Value\": \"CreditCard\",\r\n"
			    + "        \"CardType\": [\"Mastercard\", \"AmericanExpress\"]\r\n"
			    + "    },\r\n"
			    + "    \"RetrievalMethod\": {\r\n"
			    + "        \"IsValidated\": true,\r\n"
			    + "        \"Type\": \"CopyService\",\r\n"
			    + "        \"Value\": \"ChartPro\"\r\n"
			    + "    },\r\n"
			    + "    \"ReturnPreference\": {\r\n"
			    + "        \"Value\": \"CotivitiPortal\",\r\n"
			    + "        \"IsValidated\": true\r\n"
			    + "    },\r\n"
			    + "    \"SendPreference\": {\r\n"
			    + "        \"IsValidated\": true,\r\n"
			    + "        \"Checked\": true,\r\n"
			    + "        \"SendVia\": \"Mail\",\r\n"
			    + "        \"Address\": {\r\n"
			    + "            \"AddressLine1\": \"234\",\r\n"
			    + "            \"AddressLine2\": \"234\",\r\n"
			    + "            \"AttnTo\": \"242\",\r\n"
			    + "            \"City\": \"234\",\r\n"
			    + "            \"State\": \"IA\",\r\n"
			    + "            \"Zip\": \"43322-2222\"\r\n"
			    + "        },\r\n"
			    + "        \"Overrides\": []\r\n"
			    + "    },\r\n"
			    + "    \"SpecialInstructions\": {\r\n"
			    + "        \"NextReviewDate\": \""+nextReviewDate+"\",\r\n"
			    + "        \"Value\": \"My Instruction\",\r\n"
			    + "        \"UpdatedBy\": \"Ajay\"\r\n"
			    + "    },\r\n"
			    + "    \"WorkflowSettings\": {\r\n"
			    + "        \"OnlyOwnerCanWork\": true,\r\n"
			    + "        \"Owner\": \"dinesh.neeli@cotiviti.com\",\r\n"
			    + "        \"ConfirmRecordsAvailable\": {\r\n"
			    + "            \"Value\": true,\r\n"
			    + "            \"IsValidated\": true\r\n"
			    + "        },\r\n"
			    + "        \"ExcludeFromBulkSend\": {\r\n"
			    + "            \"Value\": true,\r\n"
			    + "            \"IsValidated\": true\r\n"
			    + "        },\r\n"
			    + "        \"ReasonForExclusion\": {\r\n"
			    + "            \"Value\": \"Need account number/other info added to request\",\r\n"
			    + "            \"IsValidated\": true\r\n"
			    + "        },\r\n"
			    + "        \"VerifyLettersReceived\": {\r\n"
			    + "            \"Value\": true,\r\n"
			    + "            \"IsValidated\": true\r\n"
			    + "        },\r\n"
			    + "        \"Website\": {\r\n"
			    + "            \"Value\": \"www.pega.com\",\r\n"
			    + "            \"IsValidated\": true\r\n"
			    + "        }\r\n"
			    + "    }\r\n"
			    + "}";  


		return configPayloadRG;
	}
}
